language: android
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
script:
  - "./android/gradlew build check"
before_install:
  - ./android/ci-setup.sh
  - export ANDROID_HOME=$HOME/.android/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
